export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ERROR = 'ERROR'


export const LIQUIDATE = 'LIQUIDATE'
export const LIQUIDATE_RETURNED = 'LIQUIDATE_RETURNED'

export const GET_LIQUIDATION_DATA = 'GET_LIQUIDATION_DATA'
export const LIQUIDATION_DATA_RETURNED = 'LIQUIDATION_DATA_RETURNED'

export const GET_LIQUIDATION_CANDIDATES = 'GET_LIQUIDATION_CANDIDATES'
export const LIQUIDATION_CANDIDATES_RETURNED = 'LIQUIDATION_CANDIDATES_RETURNED'

export const REFRESH_LIQUIDATION_CANDIDATES = 'REFRESH_LIQUIDATION_CANDIDATES'
export const REFRESH_LIQUIDATION_CANDIDATES_RETURNED = 'REFRESH_LIQUIDATION_CANDIDATES_RETURNED'
